version: '3'

tasks:
  test-historydb:
    dotenv: [".env"]
    cmds:
      - go test ./database/historydb -v
  
  test-til:
    dotenv: [".env"]
    cmds:
      - go test ./test/til -v

  test-synchronizer:
    dotenv: [".env"]
    cmds:
      - go test ./synchronizer -v
  
  test-statedb:
    dotenv: [".env"]
    cmds:
      - go test ./database/statedb -v
  
  test-sequencer:
    deps:
      - test-historydb
      - test-til
      - test-synchronizer
      - test-statedb