version: '3'

tasks:
  test-historydb:
    dotenv: [".env"]
    cmds:
      - go test ./database/historydb -v -count=1
  
  test-til:
    dotenv: [".env"]
    cmds:
      - go test ./test/til -v -count=1

  test-synchronizer:
    dotenv: [".env"]
    cmds:
      - go test ./synchronizer -v -count=1
  
  test-sequencer:
    cmds:
      - task: test-synchronizer
      - task: test-historydb
      - task: test-til